### ISSUE TITLE
Documentation: document API of the copilot-core library

### ISSUE THREAD

**Issue by ivanperez-keera** [Copilot-Language/copilot-core#22]
This is a subissue of Copilot-Language/copilot#66.

A lot of the code in the copilot-core package is undocumented. This makes it hard for others to navigate the API, and even for ourselves to maintain it.

A successful completion of this issue would have to consistently document, using haddock, all functions and declarations in all modules in the copilot-core package, as well as the package itself.

**Comment by fdedden** [comment]
I placed a few comments on some lines, apart from that everything looks fine.

There are a couple of commits that show 'This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.' what is up with that?

**Comment by fdedden** [comment]
Comments are looking  good.
